# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [13]:
a = 2.0 + 3.0 / 5.0
print(a)
b = (a + 10.2) - 5.0 * 2.0
print(b)
c = a / b + 33.8
print(c)
d = a / (b + c)
print(d)
e = d * 2
print(e)

2.6
2.799999999999999
34.72857142857143
0.0692805481537876
0.1385610963075752


## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [24]:
import numpy as np
lista_a = [2.0, 3.0, 5.0] + [ 10, 20, 30]
lista_a = np.array(lista_a)
print(lista_a)
lista_b = lista_a * 2
print(lista_b)
lista_c = lista_a + lista_b
print(lista_c)
lista_d = lista_a / (lista_b * lista_c)
print(lista_d)


[ 2.  3.  5. 10. 20. 30.]
[ 4.  6. 10. 20. 40. 60.]
[ 6.  9. 15. 30. 60. 90.]
[0.08333333 0.05555556 0.03333333 0.01666667 0.00833333 0.00555556]


## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [31]:
import numpy as np
a = 2.6
b = 2.799999999999999
c = 34.72857142857143
d = 0.0692805481537876
e = 0.1385610963075752
lista_exercicio_1 = [a, b, c, d, e]
print(lista_exercicio_1)
lista_raizes = np.sqrt(lista_exercicio_1)
print(lista_raizes)
lista_3 = lista_exercicio_1 + list(lista_raizes)
lista_3 = lista_exercicio_1 + [float(x) for x in lista_raizes]
print(lista_3)

[2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752]
[1.61245155 1.67332005 5.89309523 0.26321198 0.37223796]
[2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]


## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [38]:
lista_3 = [2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]
lista_4 = lista_3 * 2
array_4 = np.array(lista_4)
array_5 = array_4.reshape(5, 4)
print(array_5)

[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]]


## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [46]:
array_6 = array_5
lista_array_6 = media = np.mean(array_6, axis=0)
print(lista_array_6)

[7.88073291 2.14941306 7.88073291 2.14941306]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [51]:
import numpy as np
array_5 = array_4.reshape(5, 4)
medias = np.mean(array_5, axis=0)
lista_array_7 = array_5.tolist()
lista_array_7.append(list(medias))
array_8 = np.array(lista_array_7)
print(array_8)

[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]
 [ 7.88073291  2.14941306  7.88073291  2.14941306]]


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [55]:
import pandas as pd
array_9 = array_8.reshape(6, 4)
dataframe1 = pd.DataFrame(array_9).round(3)
print(dataframe1)

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [56]:
medias_dataframe = dataframe1.mean(axis=1)

dataframe1['media_linhas'] = medias_dataframe

print(dataframe1)

        0      1       2      3  media_linhas
0   2.600  2.800  34.729  0.069      10.04950
1   0.139  1.612   1.673  5.893       2.32925
2   0.263  0.372   2.600  2.800       1.50875
3  34.729  0.069   0.139  1.612       9.13725
4   1.673  5.893   0.263  0.372       2.05025
5   7.881  2.149   7.881  2.149       5.01500


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [57]:
ultima_linha = dataframe1.iloc[-1]
ultima_coluna = dataframe1['media_linhas']

print("Última linha:")
print(ultima_linha.describe())

print("\nÚltima coluna:")
print(ultima_coluna.describe())

Última linha:
count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64

Última coluna:
count     6.000000
mean      5.015000
std       3.758615
min       1.508750
25%       2.120000
50%       3.672125
75%       8.106688
max      10.049500
Name: media_linhas, dtype: float64


## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [58]:
dataframe1.columns = ['1', '2', '3', '4', 'media_linhas']
dataframe1.index = ['a', 'b', 'c', 'd', 'e', 'media_colunas']

print(dataframe1)

                    1      2       3      4  media_linhas
a               2.600  2.800  34.729  0.069      10.04950
b               0.139  1.612   1.673  5.893       2.32925
c               0.263  0.372   2.600  2.800       1.50875
d              34.729  0.069   0.139  1.612       9.13725
e               1.673  5.893   0.263  0.372       2.05025
media_colunas   7.881  2.149   7.881  2.149       5.01500
