# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [2]:
a = 2.0 + 3.0 / 5.0 == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a / b + 33.8 < 100
d = 5 != a / (b + c)
e = 33 == d * 2
print(a, b, c, d, e)

False True True True False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [14]:
p1 = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
x1 =['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
y1 = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
z1 = ['a',1,True,'b',0,False] > ['a',True,1]
w1 = ['a',1,True,'b',0,False] == 1
v1 = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]
print(p1, x1, y1, z1, w1, v1)

p2 = ('a',1,True,'b',0,False) != ('a',1,True,'b',0,True)
x2 =['a',1,True,'b',0,False] != ['a',1,True,'b',0,False]
y2 = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
z2 = ['a',1,True,'b',0,False] > ['a',True,2]
w2 = ['a',1,True,'b',0,False] == ['a',1,True,'b',0,False]
v2 = ['a',True,2] <= ['a',True,1] < ['a',1,True,'b',0,False]
print(p2, x2, y2, z2, w2, v2)

False True False True False True
True False True False True False


## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [28]:
import pandas as pd
dataframe1 = pd.DataFrame(
    [
        [2.600, 2.800, 34.729, 0.069, 10.04950],
        [0.139, 1.612, 1.673, 5.893, 2.32925],
        [0.263, 0.372, 2.600, 2.800, 1.50875],
        [34.729, 0.069, 0.139, 1.612, 9.13725],
        [1.673, 5.893, 0.263, 0.372, 2.05025],
        [7.881, 2.149, 7.881, 2.149, 5.01500]
    ],
    columns=['1', '2', '3', '4', 'media_linhas'],
    index=['a', 'b', 'c', 'd', 'e', 'media_colunas']
)
dataframe1.to_csv('dataframe1.csv')
dataframe2 = pd.read_csv('dataframe1.csv', index_col=0)
dataframe2 = dataframe2.round(3)
print(dataframe2)

                    1      2       3      4  media_linhas
a               2.600  2.800  34.729  0.069        10.050
b               0.139  1.612   1.673  5.893         2.329
c               0.263  0.372   2.600  2.800         1.509
d              34.729  0.069   0.139  1.612         9.137
e               1.673  5.893   0.263  0.372         2.050
media_colunas   7.881  2.149   7.881  2.149         5.015


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [30]:
import numpy as np
array_ones = np.ones(dataframe1.shape, dtype=int)
print(array_ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [32]:
df_array = dataframe1.to_numpy()
comparacao = df_array == array_ones
quantos = comparacao.sum()
print(quantos)

0


## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [33]:
df_array = dataframe1.to_numpy()
quantos_maiores = (df_array > 1).sum()
print(quantos_maiores)

22


## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [34]:
df_array = dataframe1.to_numpy()
quantos_menores_ou_iguais = (df_array <= 1).sum()
print(quantos_menores_ou_iguais)

8


## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [35]:
df_array = dataframe1.to_numpy()
quantos = ((df_array >= 0) & (df_array <= 1)).sum()
print(quantos)

8


## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [36]:
media = dataframe1['media_linhas']
quantos = (media <= 5).sum()
print(quantos)

3


## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [38]:
media = dataframe1.loc['media_colunas']
quantos = (media > 5).sum()
print(quantos)

3
